#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

cleanCase
\cp 0/alpha.water.orig 0/alpha.water

#------------------------------------------------------------------------------
