#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

wmake src/errorEstimators
wmake src/dynamicMesh
wmake src/dynamicFvMesh

wmake applications/utilities/updateMesh
wmakeLnInclude applications/utilities/reconstructParMesh
wmake applications/utilities/reconstructParMesh

wmake applications/solvers/combustion/reactingDyMFoam
wmake applications/solvers/combustion/reactingConstLewisFoam
# -----------------------------------------------------------------------------
