#!/usr/bin/env bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

if [ -z "$AMRLB_PROJECT" ]; then
    echo "AMRLB_PROJECT not set. Please set it to the root of the blastAMR repository."
    echo "For example, for blastAMR tutorials:"
    echo 'export AMRLB_PROJECT=$(git rev-parse --show-toplevel)'
    exit 1
fi
export FOAM_CODE_TEMPLATES=$AMRLB_PROJECT/etc/codeTemplates/dynamicCode
set -e
# Generate mesh with blockMesh`
runApplication blockMesh

restore0Dir
runApplication setFields

maxRef=$(foamDictionary -entry maxRefinement -value constant/dynamicMeshDict)
for i in $(seq 1 "$maxRef"); do
    runApplication -a updateMesh -overwrite
    runApplication -a setFields
done
runApplication decomposePar -cellDist

for proc in processor*; do
    ln -s $PWD/constant $PWD/$proc/constant
done

#runParallel reactingConstLewisFoam


#------------------------------------------------------------------------------
