#!/usr/bin/env bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
set -e

restore0Dir
runApplication blockMesh

if [ -z "$AMRLB_PROJECT" ]; then
    echo "AMRLB_PROJECT not set. Please set it to the root of the blastAMR repository."
    echo "For example, for blastAMR tutorials:"
    echo 'export AMRLB_PROJECT=$(git rev-parse --show-toplevel)'
    exit 1
fi
export FOAM_CODE_TEMPLATES=$AMRLB_PROJECT/etc/codeTemplates/dynamicCode

if [ "$1" = "-parallel" ]; then
    runApplication decomposePar -cellDist
    runParallel $(getApplication)
    runApplication reconstructParMesh -cellDist
    runParallel redistributePar -reconstruct -parallel
else
    runApplication $(getApplication)
fi

#------------------------------------------------------------------------------
