#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Modified tutorial run functions
#------------------------------------------------------------------------------

export AMRLB_PROJECT=$(git rev-parse --show-toplevel)
export FOAM_CODE_TEMPLATES=$AMRLB_PROJECT/etc/codeTemplates/dynamicCode

# prepare case
runApplication blockMesh

restore0Dir

runApplication setFields

# runApplication decomposePar

## run application
## commented out because script needs to be adapted anyway
# mpirun -np xx --output-filename log reactingConstLewisFoam -parallel

#------------------------------------------------------------------------------
