#!/usr/bin/env bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Modified tutorial run functions
#------------------------------------------------------------------------------

if [ -z "$AMRLB_PROJECT" ]; then
    echo "AMRLB_PROJECT not set. Please set it to the root of the blastAMR repository."
    echo "For example, for blastAMR tutorials:"
    echo 'export AMRLB_PROJECT=$(git rev-parse --show-toplevel)'
    exit 1
fi
export FOAM_CODE_TEMPLATES=$AMRLB_PROJECT/etc/codeTemplates/dynamicCode

# prepare case
runApplication blockMesh

restore0Dir

runApplication setFields

# runApplication decomposePar

## run application
## commented out because script needs to be adapted anyway
# mpirun -np xx --output-filename log reactingConstLewisFoam -parallel

#------------------------------------------------------------------------------
