#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Generate mesh with blockMesh`
runApplication blockMesh

restore0Dir
runApplication setFields

maxRef=$(foamDictionary -entry maxRefinement -value constant/dynamicMeshDict)
for i in $(seq 1 "$maxRef"); do
    runApplication -a updateMesh -overwrite
    runApplication -a setFields
done
runApplication decomposePar
mpirun -np 8 --output-filename log reactingDyMFoam -parallel

#------------------------------------------------------------------------------
