#!/bin/sh
cd "${0%/*}" || exit                         # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

runApplication decomposePar -cellDist

runParallel $(getApplication)

runApplication reconstructParMesh -cellDist
runParallel redistributePar -reconstruct -cellDist

#------------------------------------------------------------------------------
