#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

export AMRLB_PROJECT=$(git rev-parse --show-toplevel)
export FOAM_CODE_TEMPLATES=$AMRLB_PROJECT/etc/codeTemplates/dynamicCode

restore0Dir
runApplication blockMesh
runApplication topoSet
runApplication subsetMesh -overwrite c0 -patch walls
maxRef=$(foamDictionary -entry maxRefinement -value constant/dynamicMeshDict)
refineInterval=$(foamDictionary -entry refineInterval -value constant/dynamicMeshDict)
unrefineInterval=$(foamDictionary -entry unrefineInterval -value constant/dynamicMeshDict)
foamDictionary -entry refineInterval -set 1 constant/dynamicMeshDict
foamDictionary -entry unrefineInterval -set 1 constant/dynamicMeshDict
runApplication setFields
for i in $(seq 1 $maxRef); do
    runApplication -a updateMesh -overwrite
    runApplication -a setFields
done
foamDictionary -entry refineInterval -set $refineInterval constant/dynamicMeshDict
foamDictionary -entry unrefineInterval -set $unrefineInterval constant/dynamicMeshDict
cp -rT 0/polyMesh constant/polyMesh
runApplication decomposePar -constant
#runParallel interFoam

#------------------------------------------------------------------------------
